### ISSUE TITLE
Login to Portokasse fails

### ISSUE THREAD

**Issue by as19git67** [schaechinger/internetmarke#14]
Hi, since some weeks I have trouble logging into Portokasse using this npm module.
I wanted to ask if you still be able to login without errors and able to access the product list, buy and generate stamps.
Feel free to close this issue, if you don't see any current problems.

**Comment by schaechinger** [comment]
Right, the Portokasse login changed for a reason. Will update it asap.
Thanks for the issue

**Comment by schaechinger** [comment]
Issue is solved and internetmarke is released in v0.9.2

**Comment by as19git67** [comment]
I can confirm that logging into Portokasse works again. Thanks a lot for fixing it!
