### ISSUE TITLE
ProductList not yet done?

### ISSUE THREAD

**Issue by gerwinbrunner** [schaechinger/internetmarke#2]
Hi @schaechinger,

congrats for your package. I played with it for a few minutes and was able to get the balance from my post test account. Great work!!!

I looked at the code and I guess that you just started to implement the product and productlist part, but it's not yet complete, right?

Cheers,
Gerwin

**Comment by schaechinger** [comment]
HI @gerwinbrunner,

thank you! You're right, I'm noch done with the productlist implementation. I'll try to finish it this weekend and will inform you once it is live. This will be part of the release v0.3.0

**Comment by gerwinbrunner** [comment]
@schaechinger cool - thanks - I'm happy to try it :)

**Comment by schaechinger** [comment]
Hi @gerwinbrunner

The first version of the product service is pushed to [feature/prod-ws](https://github.com/schaechinger/internetmarke/tree/feature/prod-ws)
There are a few things missing but you can retrieve the product list and use products to order vouchers by now.

Have fun!

**Comment by gerwinbrunner** [comment]
@schaechinger Works like a charm. Really awesome! Thx
