### ISSUE TITLE
Checkout with PDF

### ISSUE THREAD

**Issue by gerwinbrunner** [schaechinger/internetmarke#6]
Hi,

it seem that the checkout option `PDF` does not work since the internetmarke api expects different inputs than the default one for `PNG`

**Comment by gerwinbrunner** [comment]
```
internetmarke.checkout({
      outputFormat: 'PDF',
});
```

**Comment by schaechinger** [comment]
Hi, that's right the module does not support PDFs by now.
This is the goal for v0.4 and will be implemented in the first half of may

**Comment by arieljaw12** [comment]
@schaechinger We solve this with @gerwinbrunner , since there were some parameter that were missing for the `checkoutShoppingCartPDFAsync` method.

If you add this lines you would be able to create a PDF label.

`Internetmarke.js`
```
checkout({ orderId = null, outputFormat = null } = {}) {
    ...
      throw new Error(errors.internetmarke.walletEmpty);
    }

    // It was missing the page format ID, since it's mandatory
    order = Object.assign({
      pageFormatId: 1,
    }, order);

    return ...
  }
```

and

`Position.js`
```
getPosition() {
    ...

      position.additionalInfo = this._additionalInfo
    }
    // Added stuff for PDF - START
    position.voucherLayout = this._voucherLayout;
    position.position = {
      labelX: 1,
      labelY: 1,
      page:1,
    };
    // Added stuff for PDF - END

    return position;
  }
```

Hope it helps with your next release!
Ariel
